name: skysim

channels:
    - astropy
    - conda-forge

dependencies:
    - python=3.6
    - astropy
    - Cython
    - matplotlib
    - numpy
    - scipy
    - healpy
    - pip:
        - sphinx-astropy
