name: skysim

channels:
    - astropy

dependencies:
    - astropy
    - sphinx-astropy
    - Cython
    - matplotlib
    - numpy
    - scipy
    - configparser
#   - pip:
#       - dependency_from_pip
